---
  root: true
  parser: "@typescript-eslint/parser"
  plugins:
    - "@typescript-eslint"
  extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
  rules:
    no-bitwise: error
    no-console: error
    object-shorthand:
      - error
      - never
    sort-imports:
      - error
      - ignoreDeclarationSort: true
        ignoreCase: true
    "@typescript-eslint/explicit-module-boundary-types": off
    "@typescript-eslint/no-explicit-any": off
    "@typescript-eslint/no-unused-vars":
      - error
      - argsIgnorePattern: "^_"
        varsIgnorePattern: "^_"
    indent:
      - error
      - 4
      - FunctionDeclaration:
          parameters: first
        FunctionExpression:
          parameters: first
        CallExpression:
          arguments: first
        ObjectExpression: first
        ImportDeclaration: first
        SwitchCase: 1
    no-multiple-empty-lines: error
    no-trailing-spaces: error
    lines-between-class-members:
      - error
      - always
      - exceptAfterSingleLine: true
